### ISSUE TITLE
User not registered in the Developer Dashboard

### ISSUE THREAD

**Issue by MxBlock** [Wmuga/spotify-osu-playlist-creator#1]
Tried to use the application, but encountered the following issue:

> Awaiting permissions
> Creating playlist
> undefined:1
> User not registered in the Developer Dashboard
> SyntaxError: Unexpected token U in JSON at position 0

So in index.js line 15 returns an unexpected value - error, which line 16 then incorrectly converts, or well it can't.
I have already enabled the Spotify Developer Dashboard, but I still get the same message. Could it be that the app is still in closed state/developer mode - so only the developer and trusted users can access it? Or do you have any other idea what might be going wrong?
Thanks in advance!

**Comment by Wmuga** [comment]
Oh. App is probably dead at spotify side(no account no app). You can try replacing client_id in spotify_module line 8 with your own(create app in dashboard).

I forgot this repo even exists. Probably should've archived it
